import { Flame } from "lucide-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { AirbyteTestButton } from "@/components/airbyte-test-button";
import { BookingPanelProvider } from "@/components/booking-panel-context";
import { BookingPanelToggle } from "@/components/booking-panel-toggle";
import { WorkflowToggle } from "@/components/workflow-toggle";
import { CallVenueButton } from "@/components/call-venue-button";
import { EmailVendorButton } from "@/components/email-vendor-button";
import { NavTabs } from "@/components/nav-tabs";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <BookingPanelProvider>
            <header className="shrink-0 border-b bg-background px-6 h-14 relative flex items-center">
              <div className="flex items-center shrink-0">
                <Flame className="size-5 mr-2 text-orange-500" />
                <span className="text-lg font-semibold tracking-tight">
                  Hestia
                </span>
              </div>
              <div className="absolute left-1/2 -translate-x-1/2">
                <NavTabs />
              </div>
              <div className="ml-auto flex items-center gap-2 shrink-0">
                <AirbyteTestButton />
                <CallVenueButton />
                <EmailVendorButton />
                <ThemeToggle />
                <WorkflowToggle />
                <BookingPanelToggle />
              </div>
            </header>
            <div className="flex-1 flex flex-col min-h-0">{children}</div>
          </BookingPanelProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
